// Shepard-Metzler stimulus configurations
// Format: "L1D1-L2D2-L3D3-L4D4" where L=length(2-4), D=direction

// we want:
// - 5 in range 0-30 degrees
// - 5 in 30-90
// - 5 in 90-150
// - 5 in range 150-180 degrees
// - 5 mirror
// 25 total

export const stimulusConfigs = [
  // 0-30
  {
    config: '4Z--4F-3D-3F',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: 0,
    mirror: false,
  },
  {
    config: '3Z+-3L-2D-2D',
    leftRotationX: -0.401,
    leftRotationY: 0.017,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0.419,
    rightDeltaZ: 0,
    disparity: 24,
    mirror: false,
  },
  {
    config: '3Y+-3F-2F-2U',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0.489,
    rightDeltaX: 0.314,
    rightDeltaY: 0,
    rightDeltaZ: 0.052,
    disparity: 18,
    mirror: false,
  },
  {
    config: '4Z+-3L-2B-3D',
    leftRotationX: -1.693,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 0.471,
    disparity: 27,
    mirror: false,
  },
  {
    config: '3Z--4U-4D-3L',
    leftRotationX: -0.157,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: -0.384,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: -22,
    mirror: false,
  },
  // 30-90
  {
    config: '4Z+-3U-4D-3F',
    leftRotationX: 0,
    leftRotationY: 0.122,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -0.681,
    rightDeltaZ: 0,
    disparity: -39,
    mirror: false,
  },
  {
    config: '3Y+-4F-4D-2R',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -1.414,
    rightDeltaZ: 0,
    disparity: -81,
    mirror: false,
  },
  {
    config: '4Z--4D-4F-4L',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 1.134,
    rightDeltaZ: 0,
    disparity: 65,
    mirror: false,
  },
  {
    config: '3Y--3F-2R-4U',
    leftRotationX: 0,
    leftRotationY: 1.292,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: -1.326,
    disparity: -76,
    mirror: false,
  },
  {
    config: '2Z--3R-2U-2U',
    leftRotationX: 0,
    leftRotationY: -0.279,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0.855,
    rightDeltaZ: 0,
    disparity: 49,
    mirror: false,
  },
  // 90 - 150,
  {
    config: '2X--3U-2B-4U',
    leftRotationX: -1.012,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: -2.478,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: -142,
    mirror: false,
  },
  {
    config: '2Z+-4U-4U-3L',
    leftRotationX: 0,
    leftRotationY: 0.087,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 1.728,
    rightDeltaZ: 0,
    disparity: 99,
    mirror: false,
  },
  {
    config: '4Z--4U-3L-3R',
    leftRotationX: 0,
    leftRotationY: -0.332,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 1.745,
    rightDeltaZ: 0,
    disparity: 100,
    mirror: false,
  },
  {
    config: '2X--4D-4R-3F',
    leftRotationX: 0,
    leftRotationY: -1.955,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 2.443,
    rightDeltaZ: 0,
    disparity: 140,
    mirror: false,
  },
  {
    config: '2X--4F-4L-4R',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -2.094,
    rightDeltaZ: 0,
    disparity: -120,
    mirror: false,
  },
  //150-180 degrees
  {
    config: '2Y+-4L-2D-4F',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 2.723,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: 156,
    mirror: false,
  },
  {
    config: '2Y--2L-4U-3F',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -2.967,
    rightDeltaZ: 0,
    disparity: -170,
    mirror: false,
  },
  {
    config: '3Y+-4B-2U-3U',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 2.705,
    rightDeltaZ: 0,
    disparity: 155,
    mirror: false,
  },
  {
    config: '4Z+-4B-4U-4B',
    leftRotationX: 1.414,
    leftRotationY: 1.431,
    leftRotationZ: 0.244,
    rightDeltaX: 2.897,
    rightDeltaY: -0.017,
    rightDeltaZ: 0,
    disparity: 166,
    mirror: false,
  },
  {
    config: '2X--2B-2U-3L',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 3.142,
    disparity: 180,
    mirror: false,
  },
  // mirror
  {
    config: '4X--4B-4U-4R',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 1.292,
    rightDeltaZ: 0,
    disparity: 74,
    mirror: true,
  },
  {
    config: '4Y+-2L-2B-2U',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: -1.693,
    disparity: -97,
    mirror: true,
  },
  {
    config: '2Z+-4F-2D-3F',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 3.124,
    disparity: 179,
    mirror: true,
  },
  {
    config: '2Y--4F-2L-4L',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 0.157,
    disparity: 9,
    mirror: true,
  },
  {
    config: '2Y+-4R-4B-2R',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: -3.142,
    disparity: -180,
    mirror: true,
  },
]
