// Shepard-Metzler stimulus configurations
// Format: "L1D1-L2D2-L3D3-L4D4" where L=length(2-4), D=direction

export const stimulusConfigs = [
  {
    config: '3X+-2U-4L-3D',
    leftRotationX: -0.017,
    leftRotationY: 0.506,
    leftRotationZ: 0,
    rightDeltaX: -1.588,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: -91,
    mirror: false,
  },
  {
    config: '2Z+-3B-2U-4F',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 1.449,
    rightDeltaZ: 0,
    disparity: 83,
    mirror: false,
  },
  {
    config: '4Z+-3R-4D-2B',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: -1.344,
    disparity: -77,
    mirror: false,
  },
  {
    config: '3Y--4R-4F-2R',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 1.955,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: 112,
    mirror: false,
  },
  {
    config: '2Y--2B-4U-3U',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0.297,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: 17,
    mirror: false,
  },
  {
    config: '3X+-4L-2U-4B',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 1.187,
    disparity: 68,
    mirror: false,
  },
  {
    config: '3Z--4L-3R-2R',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -1.292,
    rightDeltaZ: 0,
    disparity: -74,
    mirror: false,
  },
  {
    config: '4X+-3D-4D-3B',
    leftRotationX: 0,
    leftRotationY: -1.431,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -1.955,
    rightDeltaZ: 0,
    disparity: -112,
    mirror: false,
  },
  {
    config: '2X--3B-3U-4R',
    leftRotationX: -0.175,
    leftRotationY: -0.035,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: -0.646,
    disparity: -37,
    mirror: false,
  },
  {
    config: '4Z+-3U-2U-2R',
    leftRotationX: 0,
    leftRotationY: -1.885,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 0.733,
    disparity: 42,
    mirror: false,
  },
  {
    config: '3Z+-3R-3D-3B',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 1.972,
    rightDeltaX: 0,
    rightDeltaY: -1.204,
    rightDeltaZ: 0,
    disparity: -69,
    mirror: false,
  },
  {
    config: '3Z+-2R-3R-2L',
    leftRotationX: 0,
    leftRotationY: -1.641,
    leftRotationZ: 0,
    rightDeltaX: 0.349,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: 20,
    mirror: false,
  },
  {
    config: '4Y+-4L-3L-3R',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0.628,
    rightDeltaZ: 0,
    disparity: 36,
    mirror: false,
  },
  {
    config: '3X--2B-3U-3R',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 1.065,
    rightDeltaZ: 0,
    disparity: 61,
    mirror: false,
  },
  {
    config: '4Y--3R-3F-3U',
    leftRotationX: 0,
    leftRotationY: -0.401,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 3.142,
    disparity: 180,
    mirror: false,
  },
  {
    config: '2Z+-3F-3D-3U',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 1.222,
    rightDeltaX: 0,
    rightDeltaY: -1.571,
    rightDeltaZ: 0,
    disparity: -90,
    mirror: false,
  },
  {
    config: '3Z+-4R-3L-4D',
    leftRotationX: 0,
    leftRotationY: 0.035,
    leftRotationZ: 0.401,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 2.391,
    disparity: 137,
    mirror: false,
  },
  {
    config: '3Y+-4R-3U-4R',
    leftRotationX: 0,
    leftRotationY: -1.431,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 0.855,
    disparity: 49,
    mirror: false,
  },
  {
    config: '3X--2B-4F-2U',
    leftRotationX: 0,
    leftRotationY: 0.419,
    leftRotationZ: -1.152,
    rightDeltaX: 0.855,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: 49,
    mirror: false,
  },
  {
    config: '4Y--2L-4L-3F',
    leftRotationX: 0,
    leftRotationY: 1.71,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: -1.466,
    disparity: -84,
    mirror: false,
  },
  {
    config: '2Z+-3U-2D-2B',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 3.142,
    disparity: 180,
    mirror: false,
  },
  {
    config: '3Y+-2D-2B-2U',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: -0.297,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: -1.449,
    disparity: -83,
    mirror: false,
  },
  {
    config: '4X+-4U-3B-3L',
    leftRotationX: 0,
    leftRotationY: -1.309,
    leftRotationZ: 0.297,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 1.292,
    disparity: 74,
    mirror: false,
  },
  {
    config: '4X--4B-2U-3R',
    leftRotationX: 2.775,
    leftRotationY: 1.117,
    leftRotationZ: 0.332,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: -3.072,
    disparity: -176,
    mirror: false,
  },
  {
    config: '4Y--2R-4F-3B',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: -1.466,
    disparity: -84,
    mirror: false,
  },
  {
    config: '2Y+-4L-4D-3F',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 1.815,
    disparity: 104,
    mirror: false,
  },
  {
    config: '3Z+-3B-4L-4L',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: -0.297,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: -17,
    mirror: false,
  },
  {
    config: '3Z--4L-3D-3F',
    leftRotationX: 0.175,
    leftRotationY: 0.314,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 1.03,
    rightDeltaZ: 0,
    disparity: 59,
    mirror: false,
  },
  {
    config: '4Z--3D-4U-4R',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: -2.845,
    disparity: -163,
    mirror: false,
  },
  {
    config: '3Y+-4U-2U-4F',
    leftRotationX: 0,
    leftRotationY: 1.571,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -2.897,
    rightDeltaZ: 0,
    disparity: -166,
    mirror: false,
  },
  {
    config: '3X+-4U-2B-3R',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 1.641,
    rightDeltaZ: 0,
    disparity: 94,
    mirror: true,
  },
  {
    config: '4X+-2B-3B-3D',
    leftRotationX: 0,
    leftRotationY: 2.985,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 1.955,
    rightDeltaZ: 0,
    disparity: 112,
    mirror: true,
  },
  {
    config: '2Z+-2U-2L-4D',
    leftRotationX: 0,
    leftRotationY: 1.431,
    leftRotationZ: 1.466,
    rightDeltaX: 0,
    rightDeltaY: -3.142,
    rightDeltaZ: 0,
    disparity: -180,
    mirror: true,
  },
  {
    config: '4X+-3D-2F-3U',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -0.035,
    rightDeltaZ: 0,
    disparity: -2,
    mirror: true,
  },
  {
    config: '3Z--3U-3B-2R',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -1.431,
    rightDeltaZ: 0,
    disparity: -82,
    mirror: true,
  },
  {
    config: '4X--2L-4B-3D',
    leftRotationX: 0,
    leftRotationY: -1.571,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0.314,
    rightDeltaZ: 0,
    disparity: 18,
    mirror: true,
  },
  {
    config: '2Z+-3U-2D-4L',
    leftRotationX: -0.122,
    leftRotationY: 3.142,
    leftRotationZ: 0.297,
    rightDeltaX: 0,
    rightDeltaY: 1.204,
    rightDeltaZ: 0,
    disparity: 69,
    mirror: true,
  },
  {
    config: '4Y--4F-4R-4R',
    leftRotationX: 0,
    leftRotationY: 0.524,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 2.513,
    rightDeltaZ: 0,
    disparity: 144,
    mirror: true,
  },
  {
    config: '3Z+-3F-3D-4B',
    leftRotationX: 0,
    leftRotationY: -2.129,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -2.443,
    rightDeltaZ: 0,
    disparity: -140,
    mirror: true,
  },
  {
    config: '2Y+-3L-3B-4B',
    leftRotationX: 0,
    leftRotationY: -0.471,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -1.553,
    rightDeltaZ: 0,
    disparity: -89,
    mirror: true,
  },
  {
    config: '2X+-4F-2B-4U',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 1.134,
    rightDeltaZ: 0,
    disparity: 65,
    mirror: true,
  },
  {
    config: '2Z--4R-3R-4F',
    leftRotationX: 0,
    leftRotationY: 1.553,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -1.693,
    rightDeltaZ: 0,
    disparity: -97,
    mirror: true,
  },
  {
    config: '2X--4R-4U-3F',
    leftRotationX: 0,
    leftRotationY: 1.431,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: 0,
    mirror: true,
  },
  {
    config: '2X+-3B-4F-4U',
    leftRotationX: 0,
    leftRotationY: 0.262,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -1.693,
    rightDeltaZ: 0,
    disparity: -97,
    mirror: true,
  },
  {
    config: '3Y--2F-4U-2D',
    leftRotationX: 0,
    leftRotationY: -0.105,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 1.815,
    rightDeltaZ: 0,
    disparity: 104,
    mirror: true,
  },
  {
    config: '3X--4B-4D-2D',
    leftRotationX: 0,
    leftRotationY: -0.419,
    leftRotationZ: 1.431,
    rightDeltaX: 0,
    rightDeltaY: 0.471,
    rightDeltaZ: 0,
    disparity: 27,
    mirror: true,
  },
  {
    config: '3X--2L-3L-4F',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -1.501,
    rightDeltaZ: 0,
    disparity: -86,
    mirror: true,
  },
  {
    config: '2X+-3D-3D-4F',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0.279,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: 0,
    mirror: true,
  },
  {
    config: '3Y--4R-2D-2B',
    leftRotationX: 0,
    leftRotationY: 3.089,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 0,
    disparity: 0,
    mirror: true,
  },
  {
    config: '2X--2U-3D-4F',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0.541,
    rightDeltaZ: 0,
    disparity: 31,
    mirror: true,
  },
  {
    config: '2X--4F-2B-2F',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 1.693,
    disparity: 97,
    mirror: true,
  },
  {
    config: '4X--4B-2U-4U',
    leftRotationX: 0,
    leftRotationY: 1.536,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 0.209,
    disparity: 12,
    mirror: true,
  },
  {
    config: '3Z+-3B-3U-4U',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 1.955,
    disparity: 112,
    mirror: true,
  },
  {
    config: '2Y+-2D-2F-4F',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -1.518,
    rightDeltaZ: 0,
    disparity: -87,
    mirror: true,
  },
  {
    config: '4X+-3L-4D-2F',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -1.728,
    rightDeltaZ: 0,
    disparity: -99,
    mirror: true,
  },
  {
    config: '2Z--3R-4U-3R',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -1.745,
    rightDeltaZ: 0,
    disparity: -100,
    mirror: true,
  },
  {
    config: '2Z+-4U-3U-3D',
    leftRotationX: -0.07,
    leftRotationY: -1.641,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 2.932,
    rightDeltaZ: 0,
    disparity: 168,
    mirror: true,
  },
  {
    config: '2Z+-2F-4U-3D',
    leftRotationX: 0,
    leftRotationY: -1.379,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: 0,
    rightDeltaZ: 2.932,
    disparity: 168,
    mirror: true,
  },
  {
    config: '3Z--2D-4B-3L',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -3.142,
    rightDeltaZ: 0,
    disparity: -180,
    mirror: true,
  },
  {
    config: '3Z+-2F-3L-3L',
    leftRotationX: 0,
    leftRotationY: 0,
    leftRotationZ: 0,
    rightDeltaX: 0,
    rightDeltaY: -1.641,
    rightDeltaZ: 0,
    disparity: -94,
    mirror: true,
  },
]
